title: First Github Pages Site
author: dstan-dev
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a practice site to learn how to use Github.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  dstan-dev # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
